const PEER_ON_OPEN = "PEER_ON_OPEN";
const PEER_CONNECT = "PEER_CONNECT"; 
const PEER_ON_CONNECTION = "PEER_ON_CONNECTION"; 

const ADD_PLAYER = "ADD_PLAYER";
const REMOVE_PLAYER = "REMOVE_PLAYER";

const SWIPE_TO = "SWIPE_TO";
const SWIPE_UP = "SWIPE_UP";

export {
    SWIPE_TO,
    SWIPE_UP,
    ADD_PLAYER,
    REMOVE_PLAYER
};
